project:
  type: book

book:
  title: "Hands-On Federated Analytics"
  author: "Daniel Kapitan"
  date: "7/6/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - paradox.qmd
    - summary.qmd
    - references.qmd

bibliography: hands-on-federated-analytics.bib
csl: cell-modified.csl

format:
  html:
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
    theme:
      - brand
      - cosmo
  pdf:
    documentclass: book
    toc: true
    number-sections: true
    colorlinks: true
    
    # gives error on GitHub Actions: fonts not available on system
    # mainfont: Inter
    # sansfont: "Zilla Slab"



